name: catnote
description: CatNote - 반려묘 관리앱
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_riverpod: ^2.5.1

  # routing
  go_router: ^14.2.7

  # formatting (date/time)
  intl: ^0.19.0

  # ids
  uuid: ^4.5.1

  # image pick (camera/gallery)
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
